### ISSUE TITLE
Not able to detect exchange password change using MSGraph API

### ISSUE THREAD

**Issue by amityadav1312** [microsoftgraph/android-java-connect-sample#10]
I am using this MSConnect sample app to fetch exchange calendars and events. For an authenticated user, events are downloaded using access token but if a user changes its password, we noticed that events continue to get downloaded using previous access token.

I am not sure if we are missing something but we are able to get events with from older access_token/refresh_token even after several days of password update. Is this an expected behavior?

Is there any way to check if user has changed his password through MS Graph Android SDK, so that app can explicitly show login screen to authenticate the user again?

I am using OIDCLib library for authentication.

Thanks In Advance!!

**Comment by amityadav1312** [comment]
Do we have any update on the above issue? Please revert..

**Comment by JohnMAustin78** [comment]
Hi Amitya,
The behavior you describe is note desirable, of course.  My hunch is that it is a server side issue. Server should not be honoring the token. On the client side, the OIDCLib should be clearing it out of the cache when notified (if notified?) that the password has changed.  I'll try to replicate it using OIDC.  I've also gotten the sample updated to use the new Microsoft Authentication Library. It is not in the master branch yet. I have a bit more testing to do and will add a password change test before merging.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this sample. Please see https://github.com/microsoftgraph/msgraph-training-android for an Android sample.
