### ISSUE TITLE
Always prompting login page

### ISSUE THREAD

**Issue by jaragones** [microsoftgraph/android-java-connect-sample#11]
When I login, first attempt works as it is supposed. I enter my outlook credentials and I can send an email. If I stop the app and start again, same prompt is called and I need to select my account again before continuing.

Right now, I'm just saving access token received and next time that app is opened I recovered token as:

            AuthenticationManager auth = AuthenticationManager.getInstance();
            auth.setAccessToken(token);

Is there a better way to do it?

**Comment by JohnMAustin78** [comment]
Hi,
I've been working on a version of the sample that uses the new Microsoft Authentication Library (MSAL) into this connect sample.  It fixes the behavior you describe. It should be merged into the master branch this week.

**Comment by jaragones** [comment]
Thanks to let me know. :)
