### ISSUE TITLE
On press back button device hang.

### ISSUE THREAD

**Issue by akashKite** [microsoftgraph/android-java-connect-sample#16]
I am using this app for first time  logging. Call Connect() function for signing.
   private void connect() {

        // The sample app is having the PII enable setting on the MainActivity. Ideally, app should decide to enable Pii or not,
        // if it's enabled, it should be  the setting when the application is onCreate.
        if (mEnablePiiLogging) {
            Logger.getInstance().setEnablePII(true);
        } else {
            Logger.getInstance().setEnablePII(false);
        }

        AuthenticationManager mgr = AuthenticationManager.getInstance();

          /* Attempt to get a user and acquireTokenSilent
   * If this fails we do an interactive request
   */
        List<User> users = null;

        try {
            users = mgr.getPublicClient().getUsers();

            if (users != null && users.size() == 1) {
          /* We have 1 user */
                mUser = users.get(0);
                mgr.callAcquireTokenSilent(
                        mUser,
                        true,
                        this);
            } else {
          /* We have no user */

          /* Let's do an interactive request */
                mgr.callAcquireToken(
                        this,
                        this);
            }
        } catch (MsalClientException e) {
            Log.d(TAG, "MSAL Exception Generated while getting users: " + e.toString());
            showConnectErrorUI(e.getMessage());

        } catch (IndexOutOfBoundsException e) {
            Log.d(TAG, "User at this position does not exist: " + e.toString());
            showConnectErrorUI(e.getMessage());

        }catch (IllegalStateException e) {
                Log.d(TAG, "MSAL Exception Generated: " + e.toString());
                showConnectErrorUI(e.getMessage());

        } catch (Exception e) {
            showConnectErrorUI();
        }
    }

from this function it call.
public void callAcquireToken(Activity activity, final MSALAuthenticationCallback authenticationCallback) {
        mActivityCallback = authenticationCallback;
        mPublicClientApplication.acquireToken(
                activity, Constants.SCOPES, getAuthInteractiveCallback());
    }
after calling this function i get signing page.

![screenshot_2018-03-13-11-50-59 1](https://user-images.githubusercontent.com/12906333/37325742-276a0f94-26b5-11e8-9e07-5014fef4a22d.png)

after that i click on back button which appear on signing page.
when i click back button device hang after some time get message of not responding.  Device back button work perfect but authetication back button is not working .

**Comment by JohnMAustin78** [comment]
Interesting problem.  Honestly, I haven't spent a lot of time writing tests for your exact scenario.  I'll investigate this and update this issue with my findings.

- John Austin

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this sample. Please see https://github.com/microsoftgraph/msgraph-training-android for an Android sample.
