### ISSUE TITLE
How to manage multiple accounts?

### ISSUE THREAD

**Issue by fiasko131** [microsoftgraph/android-java-connect-sample#17]
Hello,
when I acquired an access token, is it possible to reconnect later with this one?
By this way, as for the other cloud providers I use in my app, I could manage multiple accounts.
In this [post](https://github.com/microsoftgraph/android-java-connect-sample/issues/11) it seems to be possible to realize it but the mentioned method setAccesToken (token) no longer exists?
Thanks.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this sample. Please see https://github.com/microsoftgraph/msgraph-training-android for an Android sample.
