### ISSUE TITLE
The sample is not working with Android Studio emulators.

### ISSUE THREAD

**Issue by ziroc** [microsoftgraph/android-java-connect-sample#18]
As in title.
The error is that "Chrome is not installed on the device".
Chrome indeed doesn't come installed on the Android Studio emulators. And it is not simple to install it.

What kind of Android sample is this if it is not working with the default IDE and emulator for Android?

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this sample. Please see https://github.com/microsoftgraph/msgraph-training-android for an Android sample.
